config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  
  root "grams#index"
  
  resources :grams do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    
  end
  
  
  
  
  
  
  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ActiveRecord::Base
  validates :message, presence: true
  validates :picture, presence: true
  belongs_to :user
  has_many :comments
  has_many :likes
  mount_uploader :picture, PictureUploader
  
  
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :grams
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def render_not_found(status=:not_found)
    render text: "#{status.to_s.titleize} :(", status: status
  end
  
  
  
  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  
  def new
    @comment = Comment.new
  end
  
  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?
    
    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
    
  end
  
  
end

private

def comment_params
  params.require(:comment).permit(:message)
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @grams = Gram.all
  end
  
  def new
    @gram = Gram.new
  end
  
  def create
    @gram = current_user.grams.create(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end
  
  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
  end
  
  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.update_attributes(gram_params)
    
    if @gram.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.destroy
    redirect_to root_path
    
    
    
    
  end
  
  private
  
  def gram_params
    params.require(:gram).permit(:message, :title, :picture)
  end
  
  
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private
  
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
  
  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/grams/index.html.erb
<div class="col-xs-12 gram_wrapper">
  <div class="grid-grams col-xs-12 ">
    <% @grams.each_with_index do |gram, index| %>
    <div class="gram col-xs-12 col-sm-6 col-md-4 col-lg-3" id="slide_<%= index + 1 %>" data-index="<%= index + 1 %>" >
      <%= image_tag gram.picture %>
    </div>
    <% end %>
  </div>
  
  <div class="slider-outer">
    <div class="left_gram"></div>
    <div class="slider-inner">
      <a href="#" class="left-link"><%= image_tag 'left-arrow.png' %></a>
      <div class="wrapper">
        <% @grams.last(2).each do |gram| %>
        <div class="center-wrap ">
          <div class="slider_gram">
            <%= image_tag gram.picture %>
          </div>
        </div>
        <% end %>
        <% @grams.each_with_index do |gram, index | %>
        <div class="center-wrap" id="carousel_slide_<%= index + 1 %>" data-current-user="<%= current_user %>" data-gram-id="<%= gram.id %>" data-index="<%= index + 1 %>" data-destoy-url="<%= gram_likes_path(gram) %>" data-add-url="<%= gram_likes_path(gram) %>" data-message="<%= gram.message  %>" data-title="<%= gram.title  %>">
          <div class="slider_gram">
            <%= image_tag gram.picture %>
          </div>
        </div>
        <% end %>
        <% @grams.first(2).each do |gram| %>
        <div class="center-wrap ">
          <div class="slider_gram">
            <%= image_tag gram.picture %>
          </div>
        </div>
        <% end %>
      </div>
      <a href="#" class="right-link"><%= image_tag 'right-arrow.png' %></a>
    </div>
    <div class="right_gram"></div>
  </div>
  <div class="gram-content">
    <div class="content-fade">
      <h4 id="gram-title">Chicago Skyline</h4>
      <div class="gram-description">A beautiful snap of chicago and the sears tower. I want to go back! #chicago #skyline #vacation #travel</div>
      
      <div class="gram-icons">
        <hr class="clr">
        <div class="col-xs-2 index-count"><div class="pull-left" id="index-count">13/48</div></div>
        <div class="col-xs-8 text-center"><a class="comment_button" href="#"><%= image_tag 'cha-rounded.png', class: "comment-icon" %>13 comments</a></div>
        <div class="col-xs-2 heart-count"><div class="heart pull-right"><div class="ht heart-icon"></div>525</div></div>
      </div>
    </div>
    
    
    <div class="comment-fade">
      <h4 class="gram-title">Comments</h4>
      <div class="comment-close"></div>
      <div class="add-comment">
        
      </div>
    </div>
  </div>
</div>

app/views/grams/new.html.erb
<div class="form_wrapper">
  <h1>New Gram</h1>
  
  <%= simple_form_for @gram do |f| %>
  <%= f.input :picture%>
  <%= f.input :title, placeholder: "Title", required: true, label:false  %>
  <%= f.input :message, placeholder: "Message", required: true, label:false %>
  <br>
  <%= f.submit "Post!", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/grams/show.html.erb
<%= @gram.inspect %>

app/views/layouts/_nav.html.erb
<div id="dark_header_wrap">
  <div id="dark_header">
    <div id="logo">
      <%= link_to root_url do %>
      <%= image_tag "logo.png", class: "logo"%>
      <% end %>
    </div>
    
    <div class="dark-nav nav">
      <% if current_user %>
      <%= link_to "Add Gram", new_gram_path%>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <p id="signed_in"><%= current_user.username%></p>
      
      <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
    <div class="dark-mobile_nav"></div>
    <div class="dark-mobile_nav_menu">
      <div class="dark-mobile_menu">
        <% if user_signed_in? %>
        <span><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></span>
        <% else %>
        <span><%= link_to 'Sign In', new_user_session_path %></span>
        <span><%= link_to 'Sign Up', new_user_registration_path %></span>
        <% end %>
      </div>
      <div class="dark-mobile_close">
        
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grammable2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  
</head>
<body>
  
  <% if !params[:controller].start_with?("devise") %>
  
  <%= render partial: 'layouts/nav' %>
  <%end%>
  <% if notice.present? %>
  <p class="notice"><%= notice %></p>
  <% end %>
  
  <% if alert.present? %>
  <p class="alert"><%= alert %></p>
  <% end %>
  <%= yield %>
  
  <script>(function($){
    
    $('.dark-mobile_nav').click(function() {
      $(".dark-mobile_nav_menu").animate({right: 0});
    });
    $(".dark-mobile_close").click(function() {
      $(".dark-mobile_nav_menu").animate({right: -270});
    });
    
  })(jQuery);</script>
</body>
</html>